package com.yanzhen.model;

import java.io.Serializable;
import java.util.Date;

public class MeetingRoom implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.id
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.name
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.is_projector
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Integer isProjector;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.is_pc
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Integer isPc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.is_tel
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Integer isTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.is_vidio
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Integer isVidio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.counts
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Integer counts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.status
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.create_by
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.update_time
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.create_time
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_room.img
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_room
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.id
     *
     * @return the value of meeting_room.id
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.id
     *
     * @param id the value for meeting_room.id
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.name
     *
     * @return the value of meeting_room.name
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.name
     *
     * @param name the value for meeting_room.name
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.is_projector
     *
     * @return the value of meeting_room.is_projector
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Integer getIsProjector() {
        return isProjector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.is_projector
     *
     * @param isProjector the value for meeting_room.is_projector
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setIsProjector(Integer isProjector) {
        this.isProjector = isProjector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.is_pc
     *
     * @return the value of meeting_room.is_pc
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Integer getIsPc() {
        return isPc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.is_pc
     *
     * @param isPc the value for meeting_room.is_pc
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setIsPc(Integer isPc) {
        this.isPc = isPc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.is_tel
     *
     * @return the value of meeting_room.is_tel
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Integer getIsTel() {
        return isTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.is_tel
     *
     * @param isTel the value for meeting_room.is_tel
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setIsTel(Integer isTel) {
        this.isTel = isTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.is_vidio
     *
     * @return the value of meeting_room.is_vidio
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Integer getIsVidio() {
        return isVidio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.is_vidio
     *
     * @param isVidio the value for meeting_room.is_vidio
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setIsVidio(Integer isVidio) {
        this.isVidio = isVidio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.counts
     *
     * @return the value of meeting_room.counts
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Integer getCounts() {
        return counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.counts
     *
     * @param counts the value for meeting_room.counts
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.status
     *
     * @return the value of meeting_room.status
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.status
     *
     * @param status the value for meeting_room.status
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.create_by
     *
     * @return the value of meeting_room.create_by
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.create_by
     *
     * @param createBy the value for meeting_room.create_by
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.update_time
     *
     * @return the value of meeting_room.update_time
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.update_time
     *
     * @param updateTime the value for meeting_room.update_time
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.create_time
     *
     * @return the value of meeting_room.create_time
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.create_time
     *
     * @param createTime the value for meeting_room.create_time
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_room.img
     *
     * @return the value of meeting_room.img
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_room.img
     *
     * @param img the value for meeting_room.img
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }
}