package com.yanzhen.model;

import java.io.Serializable;

public class MeetingUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_user.id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_user.meeting_id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    private Integer meetingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column meeting_user.user_id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    private Integer userId;


    //添加相关会议对象
    private MeetingInfo meetingInfo;

    public MeetingInfo getMeetingInfo() {
        return meetingInfo;
    }

    public void setMeetingInfo(MeetingInfo meetingInfo) {
        this.meetingInfo = meetingInfo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table meeting_user
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_user.id
     *
     * @return the value of meeting_user.id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_user.id
     *
     * @param id the value for meeting_user.id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_user.meeting_id
     *
     * @return the value of meeting_user.meeting_id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    public Integer getMeetingId() {
        return meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_user.meeting_id
     *
     * @param meetingId the value for meeting_user.meeting_id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    public void setMeetingId(Integer meetingId) {
        this.meetingId = meetingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column meeting_user.user_id
     *
     * @return the value of meeting_user.user_id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column meeting_user.user_id
     *
     * @param userId the value for meeting_user.user_id
     *
     * @mbggenerated Sun Jul 04 10:13:37 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}