package com.yanzhen.mapper;

import com.yanzhen.model.Dept;
import com.yanzhen.model.Node;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("deptDao")
public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insertSelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    Dept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKeySelective(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKey(Dept record);


    /**
     * 查询所有的部门信息
     */
    List<Dept> queryDeptAll();

    /**
     * 根据父节点查询下面的集合信息
     * @param fjd
     * @return
     */
    List<Dept> queryListByFid(@Param("fjd") Integer fjd);


    /**
     * 查询部门树信息
     */
    List<Node> queryDeptTree();
}