package com.yanzhen.mapper;

import com.yanzhen.model.MeetingUser;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

import java.util.List;

@Component("meetingUserDao")
public interface MeetingUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_user
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_user
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insert(MeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_user
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insertSelective(MeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_user
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    MeetingUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_user
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKeySelective(MeetingUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meeting_user
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKey(MeetingUser record);


    /**
     * 根据会议id删除参会人员
     */
    int deleteMeetUserByMeetId(@Param("meetId") Integer meetId);

    /**
     * 批量添加参会人员
     */
    int insertPathInfo(List<MeetingUser> meetingUserList) ;
}