package com.yanzhen.mapper;

import com.yanzhen.model.PcInfo;

public interface PcInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insert(PcInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insertSelective(PcInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    PcInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKeySelective(PcInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKey(PcInfo record);
}