package com.yanzhen.mapper;

import com.yanzhen.model.ProjectorInfo;

public interface ProjectorInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projector_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projector_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insert(ProjectorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projector_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int insertSelective(ProjectorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projector_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    ProjectorInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projector_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKeySelective(ProjectorInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table projector_info
     *
     * @mbggenerated Tue Aug 24 21:59:52 CST 2021
     */
    int updateByPrimaryKey(ProjectorInfo record);
}